name: iOS

on:
  pull_request:
    branches:
      - prod

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: npm install
      - run: xcode-select -p
      - run: pod install
        working-directory: ios
        name: Install pod dependencies
      - name: Build iOS (debug)
        run: "xcodebuild \
          -workspace ios/reactgitactions.xcworkspace \
          -scheme reactgitactions \
          clean archive \
          -sdk iphoneos \
          -configuration Debug \
          -UseModernBuildSystem=NO \
          -archivePath $PWD/reactgitactions \
          CODE_SIGNING_ALLOWED=NO"
      - name: Archive Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: reactgitactions
          path: reactgitactions.xcarchive
      - name: Upload to TestFlight
        run: |
          sudo gem install fastlane
          fastlane pilot upload --ipa reactgitactions.xcarchive/Products/Applications/reactgitactions.app --username ${{ secrets.APPLE_ID }} --skip_submission
        env:
          FASTLANE_DONT_STORE_PASSWORD: true
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.APP_SPECIFIC_PASSWORD }}
