name: iOS

on:
  pull_request:
    branches:
      - prod

jobs:
  build-ios:
    runs-on: [self-hosted, macos]
    steps: 
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Install pod dependencies
        run: |
          cd ios && pod install
      - name: Build app
        run: |       
          xcodebuild -workspace reactgitactions.xcworkspace -scheme reactgitactions archive -archivePath reactgitactions.xcarchive -allowProvisioningUpdates
          xcodebuild -exportArchive -archivePath ./reactgitactions.xcarchive -exportPath . -exportOptionsPlist reactgitactions/Info.plist
          mv reactgitactions.ipa ../reactgitactions.ipa
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: reactgitactions.ipa
          path: ios/build/