name: iOS

on:
  pull_request:
    branches:
      - prod

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: npm install
      - run: xcode-select -p
      - run: pod install
        working-directory: ios
        name: Install pod dependencies
      - name: Build iOS (debug)
        run: "xcodebuild \
          -workspace ios/reactgitactions.xcworkspace \
          -scheme reactgitactions \
          clean archive \
          -sdk iphoneos \
          -configuration Debug \
          -UseModernBuildSystem=NO \
          -archivePath $PWD/reactgitactions \
          CODE_SIGNING_ALLOWED=NO"
      - name: Generate IPA
        run: "xcodebuild \
          -exportArchive \
          -archivePath $PWD/reactgitactions.xcarchive \
          -exportOptionsPlist ExportOptions.plist \
          -exportPath $PWD"
      - name: Archive Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: reactgitactions
          path: reactgitactions.xcarchive
      - name: Install app-store-deploy
        run: npm install -g app-store-deploy
      - name: Upload to TestFlight
        run: |
          app-store-deploy \
            -i ${{ secrets.APPLE_ID }} \
            -a ${{ secrets.APPLE_TEAM_ID }} \
            -p ${{ secrets.APP_SPECIFIC_PASSWORD }} \
            -q \
            -b "path/to/reactgitactions.ipa"
