name: iOS

on:
  pull_request:
    branches:
      - prod

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-
          
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      
      - run: npm install
      - run: xcode-select -p
      - run: pod install
        working-directory: ios
        name: Install pod dependencies
      - name: Build iOS (debug)
        run: "xcodebuild \
          -workspace ios/reactgitactions.xcworkspace \
          -scheme reactgitactions \
          -configuration Debug \
          -sdk iphoneos \
          -archivePath $PWD/reactgitactions.xcarchive \
          clean archive \
          CODE_SIGNING_ALLOWED=NO"
      - name: Export .ipa
        run: "xcodebuild \
          -exportArchive \
          -archivePath $PWD/reactgitactions.xcarchive \
          -exportPath $PWD/reactgitactions \
          -exportOptionsPlist ios/"
      - name: Upload .ipa
        uses: actions/upload-artifact@v2
        with:
          name: reactgitactions.ipa
          path: ios/reactgitactions/*.ipa
