name: iOS

on:
  pull_request:
    branches:
      - prod

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: npm install
      - run: xcode-select -p
      - run: pod install
        working-directory: ios
        name: Install pod dependencies
      - name: Build iOS (debug)
        run: |
          xcodebuild \
            -workspace ios/reactgitactions.xcworkspace \
            -scheme reactgitactions \
            clean archive \
            -sdk iphoneos \
            -configuration Debug \
            -UseModernBuildSystem=NO \
            -archivePath $PWD/reactgitactions \
            CODE_SIGNING_ALLOWED=NO
      - name: Create .ipa file
        run: |
          xcodebuild \
            -exportArchive \
            -archivePath $PWD/reactgitactions.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath $PWD/ipa-output

      - name: Upload .ipa artifact
        uses: actions/upload-artifact@v2
        with:
          name: reactgitactions.ipa
          path: ios/ipa-output/reactgitactions.ipa
