name: Continuous Integration

on:
  push:
    branches:
      - prod
  pull_request:
    branches:
      - prod

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  build-android:
    needs: test
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: Install npm dependencies
        run: |
          npm install
      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleRelease
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
  build-ios:
    needs: test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install npm dependencies
        run: |
          npm install
      - name: Build iOS Release
        run: |
          cd ios && pod install --repo-update
          xcodebuild -workspace react-gitactions.xcworkspace -scheme react-gitactions -sdk iphoneos -configuration Release archive -archivePath $PWD/build/react-gitactions.xcarchive
          xcodebuild -exportArchive -archivePath $PWD/build/react-gitactions.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath $PWD/build
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: react-gitactions.ipa
          path: ios/build/react-gitactions.ipa